name: rag-env
channels:
  - conda-forge
dependencies:
  - python=3.14
  - pip
  - pip:
    - langchain
    - langchain-community
    - langchain-openai
    - chromadb
    - ragas
    - pyyaml
    - pandas
    - numpy
    - scikit-learn
    - rank-bm25
    - openai
    - fastapi
    - uvicorn